### ISSUE TITLE
Вывод в форме массива

### ISSUE THREAD

**Issue by arimanr** [core01/UsersOnline#1]
Добрый день, собрал пакет на тестовом сайте (modx 4.5.0rc1) Сниппет при некэшированном вызове [[!getOnlineUsers?]] выдает массив данных пользователя (поскольку сайт тестовый пользователь только один - админ, постепенно добавлю различных учеток). Попытка указать свой шаблон через &tpl="OnlineUsersList" ни к чему не привела, а моих знаний сильно не хватает, чтобы доработать сниппет самостоятельно. Конечно, не исключено, что я сам что-то не то делаю.

Добавить некий начальный шаблон с возможностью ограничивать вывод числа пользователей через системную настройку было бы не плохо. Насколько понял, производится вывод списка всех пользователей, находящихся онлайн, что может быть удобно при показе в футере форумной страницы, но на рабочих проектах выводить даже сотню имен уже проблемно из соображений эстетики. Сриншотов работы не смог найти, соответственно возникает вопрос можно ли перевести сниппет в режим работы:

Пользователи онлайн:
admin, kpoJlik, zero, matata, UtKin...
Всего 72 (зарегистрированные: 20, гости: 50, роботы: 2)

**Comment by core01** [comment]
Добрый день, версия modx у Вас странная =)
Сниппет является оберткой для сниппета pdoUsers, поэтому за оформление отвечает именно он.
Выполните сниппет следующим образом, это должно дать понимание как нужно оформить ваш чанк OnlineUsersList: 

```
[[!getOnlineUsers? &tpl=`@INLINE <p>Имя - [[+fullname]], ID - [[+id]]</p>`]] 
```

Сниппет не имеет своих собственных параметров, кроме contexts и timeInterval, все остальные параметры передаются напрямую [pdoUsers](http://docs.modx.pro/components/pdotools/snippets/pdousers#%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B).

**Comment by arimanr** [comment]
Через inline работает. В чанке OnlineUsersList указывал именно `<p>[[+fullname]]</p>` но работать не стал (Почистил вручную папку кэш начал работать при указании чанка). Версия modx странная, да)) 

Я правильно понимаю, что сниппет будет работать со всеми параметрами pdoUsers, просто ограничивая выборку по времени с обновления сессии? То есть через &groups можно указать кто из администраторов и модераторов сейчас на сайте. Ага, с &wrapIfEmpty работает отлично.
Спасибо, теперь все стало понятно! 

Еще вопрос. Появится ли в сниппете подсчет "гостей" (например, через суммирование `&groups=`аноним``) или предполагается, что он будет работать исключительно со списками?

**Comment by core01** [comment]
> Я правильно понимаю, что сниппет будет работать со всеми параметрами pdoUsers, просто ограничивая выборку по времени с обновления сессии?

Да, но только не по времени обновления сессии, а при любом действии, когда срабатывает OnMODXInit, т.е. - всегда.

> То есть через &groups можно указать кто из администраторов и модераторов сейчас на сайте.

Да

> Появится ли в сниппете подсчет "гостей"

Возможно, пока ждем отзывов от пользователей, что бы определить дальнейший вектор развития.

**Comment by arimanr** [comment]
Понятно. Еще раз спасибо!
